//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJYM_WebApplication.Models
{
    using DJYM_WebApplication.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_COMPRA : IEntidadConClavePrimaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA_COMPRA()
        {
            this.DETALLE_FACTURA_COMPRA = new HashSet<DETALLE_FACTURA_COMPRA>();
            this.REPORTE_COMPRAS = new HashSet<REPORTE_COMPRAS>();
        }
    
        public int Numero { get; set; }
        public Nullable<int> NITProveedor { get; set; }
        public Nullable<int> DocumentoEmpleado { get; set; }
        public Nullable<decimal> TotalVenta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int ClavePrimaria => Numero; 

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACTURA_COMPRA> DETALLE_FACTURA_COMPRA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE_COMPRAS> REPORTE_COMPRAS { get; set; }
    }
}
