//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJYM_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACION_CAJA
    {
        public int Codigo { get; set; }
        public Nullable<int> NumeroCajaRegistradora { get; set; }
        public Nullable<decimal> ValorBase { get; set; }
        public Nullable<decimal> ValorCierre { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual CAJA_REGISTRADORA CAJA_REGISTRADORA { get; set; }
    }
}
