//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJYM_WebApplication.Models
{
    using DJYM_WebApplication.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR : IEntidadConClavePrimaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.FACTURA_COMPRA = new HashSet<FACTURA_COMPRA>();
        }
    
        public int NIT { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public string NumeroCelular { get; set; }
        public string Direccion { get; set; }
        public int ClavePrimaria => NIT;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_COMPRA> FACTURA_COMPRA { get; set; }
    }
}
