//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJYM_WebApplication.Models
{
    using DJYM_WebApplication.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE : IEntidadConClavePrimaria
    {
        public int Numero { get; set; }
        public Nullable<int> CodigoPeriodo { get; set; }
        public int ClavePrimaria => Numero; 

        public virtual PERIODO PERIODO { get; set; }
        public virtual REPORTE_COMPRAS REPORTE_COMPRAS { get; set; }
        public virtual REPORTE_ROTACION REPORTE_ROTACION { get; set; }
        public virtual REPORTE_VENTAS REPORTE_VENTAS { get; set; }
    }
}
