//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJYM_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_FACTURA_VENTA()
        {
            this.REPORTE_ROTACION = new HashSet<REPORTE_ROTACION>();
        }
    
        public int NumeroFactura { get; set; }
        public int CodigoProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual FACTURA_VENTA FACTURA_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE_ROTACION> REPORTE_ROTACION { get; set; }
    }
}
